### PR TITLE
HTTPS Quality of Life Improvements

### PR DESCRIPTION
**Pull request by bpar476**
I've migrated from the classic load balancer to the application load balancer and implemented listeners that will default redirect HTTP -> HTTPS if HTTPS is enabled. I also removed the TomcatScheme parameter and automatically set the Tomcat scheme based on if a certificate is supplied. This may not be desired if we want to support customers bringing their own load balancer in front of the ALB.

### CODE REVIEW

**Review by nanux — CHANGES_REQUESTED** [review]
I think it would be good to add `param` set to https://github.com/atlassian/quickstart-atlassian-jira/tree/develop/ci/params so we can test it easily in CI.

I wasn't able to find a specific ticket for Jira ALB but it is worth documenting it on https://bulldog.internal.atlassian.com/browse/DCD-245 or split a new one from the ticket.

How does this work for the migration path? Can you just replace a previous deployment with the new one with ALB?

Again the doc update is required (@ddomingorh). Right now we are showing `Internal ELB` in the diagram, it would be better to be explicit and show ALB in the diagram, so customers are clearer in what they are getting with the template. Should we do some kind of promo for this (@steveathon)?

**Comment by bpar476** [comment]
I dug up this ticket for Jira: https://bulldog.internal.atlassian.com/secure/RapidBoard.jspa?rapidView=687&projectKey=DCD&view=detail&selectedIssue=DCD-248

Adding param set is a great idea. I can look into that. I should be able to adapt some of the previous build stuff I did for that parameter set to the current builds.

Migration path I hadn't thought of 🤔 I might just test it and update stack with update template and see what happens.

Happy to work together with Don for doc update for both these changes.

**Comment by bpar476** [comment]
Build failed because load balancer name was too long 🤦‍♂ https://server-syd-bamboo.internal.atlassian.com/browse/DCD-AWSJIRA27-DEPLOY-2/log

**Comment by bpar476** [comment]
After a quick test, for jira, migration is not possible. You're not allowed to change the resource type. However a migration may be possible for confluence.

**Comment by bpar476** [comment]
Build has been implemented and tested and is now passing :)

**Comment by bpar476** [comment]
I've also updated the description for SSLCertificateARN so that it includes that it configures Jira for SSL as well.

**Comment by bpar476** [comment]
@nanux Build is all set up now in ZDCD and succeeding. We need to merge the bamboo specs but are we good to merge this PR now?

**Review by nanux — APPROVED** [review]

**Pull request merged**
