### PR TITLE
DCD-661: minor doc fixes

### PR DESCRIPTION
**Pull request by ddomingorh**
Just a few quick fixes to the some descriptions:
- added more info for Ansible customizations
- fixed other descriptions for compliance with AWS docs standards

### CODE REVIEW

**Comment by bpar476** [comment]
Are we not allowed to put `(Optional)` in our parameters  😮  Is there a link to the reasoning for this?

**Review by bpar476 — APPROVED** [review]
All good, however I would like to understand why we can't put `(Optional)` in our parameters when they are indeed optional. I feel like it could be confusing for customers.

**Review by theghostwhoforks — APPROVED** [review]
Is rermoving optional from description fields an Amazon Quickstart recommendation now?

**Comment by ddomingorh** [comment]
> Are we not allowed to put `(Optional)` in our parameters 😮 Is there a link to the reasoning for this?
@tarka @bpar476 

This came out of previous review by AWS docs. They prefer we don't use punctuation or the string `(Optional)` in the `default` field. They seem to be ok with us using it in the `Description` or `Label` fields.

**Pull request merged**
